img=imread('cameraman.tif');
b1=bitget(img,1);
b2=bitget(img,2);
b3=bitget(img,3);
b4=bitget(img,4);
b5=bitget(img,5);
b6=bitget(img,6);
b7=bitget(img,7);
b8=bitget(img,8);

subplot(3,3,1)
imshow(img)
title('Original Image')
subplot(3,3,2)
imshow(logical(b1))
title('b1')
subplot(3,3,3)
imshow(logical(b2))
title('b2')
subplot(3,3,4)
imshow(logical(b3))
title('b3')
subplot(3,3,5)
imshow(logical(b4))
title('b4')
subplot(3,3,6)
imshow(logical(b5))
title('b5')
subplot(3,3,7)
imshow(logical(b6))
title('b6')
subplot(3,3,8)
imshow(logical(b7))
title('b7')
subplot(3,3,9)
imshow(logical(b8))
title('b8')