img=imread('cameraman.tif');
b1=mod(img,2);
b2=mod(bitsrl(img,1),2);
b3=mod(bitsrl(img,2),2);
b4=mod(bitsrl(img,3),2);
b5=mod(bitsrl(img,4),2);
b6=mod(bitsrl(img,5),2);
b7=mod(bitsrl(img,6),2);
b8=mod(bitsrl(img,7),2);

subplot(3,3,1)
imshow(img)
title('Original Image')
subplot(3,3,2)
imshow(logical(b1))
title('b1')
subplot(3,3,3)
imshow(logical(b2))
title('b2')
subplot(3,3,4)
imshow(logical(b3))
title('b3')
subplot(3,3,5)
imshow(logical(b4))
title('b4')
subplot(3,3,6)
imshow(logical(b5))
title('b5')
subplot(3,3,7)
imshow(logical(b6))
title('b6')
subplot(3,3,8)
imshow(logical(b7))
title('b7')
subplot(3,3,9)
imshow(logical(b8))
title('b8')